Repository Hongik-Human-Developer/algorithm_study, pull requests merged in 2021-02, with the labels that each got.

#28 [ADD] Day6 all solved
  jangwon/js_study/Day6/problem1.md
  jangwon/js_study/Day6/problem2.md
  jangwon/js_study/Day6/problem3.md
  jangwon/js_study/Day6/problem4.md
  jangwon/js_study/Day6/problem5.md
  problem/Day7/problem.md
Labels: DONE

#29 [ADD] Day7 solved
  jangwon/js_study/Day7/problem.5.md
  jangwon/js_study/Day7/problem1.md
  jangwon/js_study/Day7/problem2.md
  jangwon/js_study/Day7/problem3.md
  jangwon/js_study/Day7/problem4.md
  problem/Day7/problem.md
  problem/Day8/problem1.md
Labels: DONE

#33 [ADD] Day8, problem2, problem4 not done
  jangwon/hankerRank/Warm-up-Challenges/Counting_valley.js
  jangwon/programmers/Day1/day1.md
  jangwon/programmers/Day2/jsfile.js
  jangwon/programmers/Day2/problem1.md
  jangwon/programmers/Day2/problem2.md
  jangwon/programmers/Day2/problem3.md
  jangwon/programmers/Day3/jsfile.js
  jangwon/programmers/Day3/problem1.md
  jangwon/programmers/Day3/problem2.md
  jangwon/programmers/Day3/problem3.md
  jangwon/programmers/Day4/jsfile.js
  jangwon/programmers/Day4/problem1.md
  jangwon/programmers/Day4/problem2.md
  jangwon/programmers/Day4/problem3.md
  jangwon/programmers/Day5/problem1.md
  jangwon/programmers/Day5/problem2.md
  jangwon/programmers/Day5/problem3.md
  jangwon/programmers/Day5/problem4.md
  jangwon/programmers/Day5/problem5.md
  jangwon/programmers/Day6/problem1.md
  jangwon/programmers/Day6/problem2.md
  jangwon/programmers/Day6/problem3.md
  jangwon/programmers/Day6/problem4.md
  jangwon/programmers/Day6/problem5.md
  jangwon/programmers/Day7/problem1.md
  jangwon/programmers/Day7/problem2.md
  jangwon/programmers/Day7/problem3.md
  jangwon/programmers/Day7/problem4.md
  jangwon/programmers/Day7/problem5.md
  jangwon/programmers/Day8/problem1.md
  jangwon/programmers/Day8/problem2.md
  jangwon/programmers/Day8/problem3.md
  jangwon/programmers/Day8/problem4.md
Labels: - ing, Not yet

#32 [NOT DONE]Day7 solved
  minhwan/javaStudy/day7.md
Labels: - ing, Not yet

#37 [ADD] Day9 problem2 not done, stack
  jangwon/Data-Structure/Stack/stack.md
  jangwon/programmers/Day9/problem1.md
  jangwon/programmers/Day9/problem2.md
  problem/Day9/problem.md
Labels: - ing, Not yet

#40 [ADD] Day11 , Day10 problem2 not done
  jangwon/programmers/Day10/problem1.md
  problem/Day10/problem.md
  problem/Day11/problem.md
Labels: - ing, Not yet

#45 [ADD] leetCode Array problem , Programmers Day12 Problem3
  jangwon/DataStructure&Algorithm/Binary-Searching/binaryTree.md
  jangwon/DataStructure&Algorithm/Brute-force/brute_force.md
  jangwon/DataStructure&Algorithm/Dynamic-programming/DynamicProgramming.md
  jangwon/DataStructure&Algorithm/Kruskal_Algorithm/Kruskal_Algorithm.md
  jangwon/DataStructure&Algorithm/Searching/bfs.md
  jangwon/DataStructure&Algorithm/Searching/dfs.md
  jangwon/DataStructure&Algorithm/Union-find/disjointSet.js
  jangwon/DataStructure&Algorithm/Union-find/union-find.md
  jangwon/leetcode/Array/Find_All_Numbers.md
  jangwon/leetcode/Array/In-place-operation/Replace.md
  jangwon/leetcode/Array/Problem/Find_Number.md
  jangwon/leetcode/Array/Problem/MajorityElement.md
  jangwon/leetcode/Array/Problem/removeArray.md
  jangwon/leetcode/Array/Problem/twoSum.md
  jangwon/programmers/Day12/problem3.md
  problem/Day12/problem.md
Labels: Not yet

#47 [ADD] day4 solved
  sungjun/day4.py
Labels: - ing

#46 Day12 [Hash]
  hyejun/JavaStudy/Data structure/Hash/Hash.md
  hyejun/JavaStudy/Programmers (문제)/day12.md
  hyejun/JavaStudy/Source Code/spy.java
  hyejun/JavaStudy/Source Code/전화번호목록.java
Labels: - ing

#49 [ADD] day4 solved
  sungjun/day4.py
Labels: DONE

#50 [ADD] Day13 problem 1 , Greedy Alogorithm
  jangwon/This_is_Coding_test/greedy/1이_될때_까지.md
  jangwon/This_is_Coding_test/greedy/가장큰수.md
  jangwon/This_is_Coding_test/숫자카드게임.md
  jangwon/leetcode/Greedy/MinimumCosttoMoveChipstoTheSame-Position.md
  jangwon/leetcode/Greedy/Split-a-String-in-Balanced-Strings.md
  jangwon/programmers/Day13/problem.md
Labels: - ing
